maintainer        "Sebastian Wendel, SourceIndex IT-Services"
maintainer_email  "packages@sourceindex.de"
license           "Apache 2.0"
description       "Installs and configures Graylog2 < 0.9.6"
version           "0.0.22"
recipe            "graylog2", "Installs and configures Graylog2"

supports "ubuntu"
depends "apt"
depends "java"
depends "apache2"
depends "elasticsearch"
depends "mongodb"
